ALTER FUNCTION dbo.SafeDateConvert(@input NVARCHAR(255))
RETURNS DATETIME
AS
BEGIN
    RETURN COALESCE(
        TRY_CONVERT(DATETIME, @input, 120),
        TRY_CONVERT(DATETIME, TRY_CONVERT(DATETIME2, @input, 126))
    );
END